<a href="https://colab.research.google.com/github/kimdfarm/FailBeakjoon/blob/main/inclass/03w_B_tue_0319_dataframe_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 03주차 수업

## 데이터프레임 정보와 수정

In [10]:
!git clone https://github.com/ai7dnn/data/

fatal: destination path 'data' already exists and is not an empty directory.

In [72]:
import pandas as pd
df = pd.read_csv('./data/2016년졸음운전.csv', encoding='euc-kr', index_col=0)
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [15]:
df.dtypes

사고(건)    int64
사망(명)    int64
부상(명)    int64
dtype: object

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 2016년1월 to 2016년12월
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사고(건)   12 non-null     int64
 1   사망(명)   12 non-null     int64
 2   부상(명)   12 non-null     int64
dtypes: int64(3)
memory usage: 384.0+ bytes

In [17]:
df.describe()

            사고(건)      사망(명)       부상(명)
count   12.000000  12.000000   12.000000
mean   202.750000   8.166667  408.250000
std     23.014324   3.186144   60.051682
min    168.000000   4.000000  328.000000
25%    186.000000   5.750000  363.500000
50%    200.000000   7.000000  402.500000
75%    219.500000  10.500000  441.250000
max    239.000000  13.000000  522.000000

In [18]:
df.T

연월,2016년1월,2016년2월,2016년3월,2016년4월,2016년5월,2016년6월,2016년7월,2016년8월,2016년9월,2016년10월,2016년11월,2016년12월
사고(건),192,174,217,216,239,200,227,230,187,183,200,168
사망(명),5,6,7,7,13,12,9,7,13,10,5,4
부상(명),387,328,435,419,522,362,460,490,347,367,418,364

In [19]:
df.sum()

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [20]:
df.sum(axis=0)

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [21]:
df.sum(axis=1)

연월
2016년1월     584
2016년2월     508
2016년3월     659
2016년4월     642
2016년5월     774
2016년6월     574
2016년7월     696
2016년8월     727
2016년9월     547
2016년10월    560
2016년11월    623
2016년12월    536
dtype: int64

In [22]:
df.cumsum(axis=0)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     366     11    715
2016년3월     583     18   1150
2016년4월     799     25   1569
2016년5월    1038     38   2091
2016년6월    1238     50   2453
2016년7월    1465     59   2913
2016년8월    1695     66   3403
2016년9월    1882     79   3750
2016년10월   2065     89   4117
2016년11월   2265     94   4535
2016년12월   2433     98   4899

In [23]:
df.cumsum(axis=1)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192    197    584
2016년2월     174    180    508
2016년3월     217    224    659
2016년4월     216    223    642
2016년5월     239    252    774
2016년6월     200    212    574
2016년7월     227    236    696
2016년8월     230    237    727
2016년9월     187    200    547
2016년10월    183    193    560
2016년11월    200    205    623
2016년12월    168    172    536

In [24]:
df.mean()

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [25]:
df.mean(axis=0)

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [26]:
df.mean(axis=1)

연월
2016년1월     194.666667
2016년2월     169.333333
2016년3월     219.666667
2016년4월     214.000000
2016년5월     258.000000
2016년6월     191.333333
2016년7월     232.000000
2016년8월     242.333333
2016년9월     182.333333
2016년10월    186.666667
2016년11월    207.666667
2016년12월    178.666667
dtype: float64

In [27]:
df.mean(axis=None)

np.float64(206.38888888888889)

In [28]:
df.max(axis=0)

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [29]:
df.max(axis=1)

연월
2016년1월     387
2016년2월     328
2016년3월     435
2016년4월     419
2016년5월     522
2016년6월     362
2016년7월     460
2016년8월     490
2016년9월     347
2016년10월    367
2016년11월    418
2016년12월    364
dtype: int64

In [30]:
df.max(axis=None)

522

In [31]:
df.min(axis=0)

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [32]:
df.min(axis=1)

연월
2016년1월      5
2016년2월      6
2016년3월      7
2016년4월      7
2016년5월     13
2016년6월     12
2016년7월      9
2016년8월      7
2016년9월     13
2016년10월    10
2016년11월     5
2016년12월     4
dtype: int64

In [33]:
df.min(axis = None)

4

In [35]:
df[['사망(명)','부상(명)']].sum(axis=1)

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

In [36]:
df.iloc[:,1:].sum(axis=1)

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

In [43]:
df2 = df.copy()
df2['제해자수'] = df[['사망(명)','부상(명)']].sum(axis=1)
df2

          사고(건)  사망(명)  부상(명)  제해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368

In [44]:
df2.loc['총계'] = df2.sum(axis=0)
df2

          사고(건)  사망(명)  부상(명)  제해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368
총계         2433     98   4899  4997

In [47]:
df2.sum()

사고(건)    4866
사망(명)     196
부상(명)    9798
제해자수     9994
dtype: int64

In [49]:
df2.loc['통계'] =df2.sum(axis=0)
df2

          사고(건)  사망(명)  부상(명)   제해자수
연월
2016년1월     192      5    387    392
2016년2월     174      6    328    334
2016년3월     217      7    435    442
2016년4월     216      7    419    426
2016년5월     239     13    522    535
2016년6월     200     12    362    374
2016년7월     227      9    460    469
2016년8월     230      7    490    497
2016년9월     187     13    347    360
2016년10월    183     10    367    377
2016년11월    200      5    418    423
2016년12월    168      4    364    368
총계         2433     98   4899   4997
통계         9732    392  19596  19988

## 논리 인덱싱

In [50]:
df2 > 10

          사고(건)  사망(명)  부상(명)  제해자수
연월
2016년1월    True  False   True  True
2016년2월    True  False   True  True
2016년3월    True  False   True  True
2016년4월    True  False   True  True
2016년5월    True   True   True  True
2016년6월    True   True   True  True
2016년7월    True  False   True  True
2016년8월    True  False   True  True
2016년9월    True   True   True  True
2016년10월   True  False   True  True
2016년11월   True  False   True  True
2016년12월   True  False   True  True
총계         True   True   True  True
통계         True   True   True  True

In [51]:
df2[df2 > 10]

          사고(건)  사망(명)  부상(명)   제해자수
연월
2016년1월     192    NaN    387    392
2016년2월     174    NaN    328    334
2016년3월     217    NaN    435    442
2016년4월     216    NaN    419    426
2016년5월     239   13.0    522    535
2016년6월     200   12.0    362    374
2016년7월     227    NaN    460    469
2016년8월     230    NaN    490    497
2016년9월     187   13.0    347    360
2016년10월    183    NaN    367    377
2016년11월    200    NaN    418    423
2016년12월    168    NaN    364    368
총계         2433   98.0   4899   4997
통계         9732  392.0  19596  19988

In [57]:
[True]*6 + [False]*7

[True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [62]:
df2[[True]*8 + [False]*6]

         사고(건)  사망(명)  부상(명)  제해자수
연월
2016년1월    192      5    387   392
2016년2월    174      6    328   334
2016년3월    217      7    435   442
2016년4월    216      7    419   426
2016년5월    239     13    522   535
2016년6월    200     12    362   374
2016년7월    227      9    460   469
2016년8월    230      7    490   497

In [64]:
df2['제해자수'] > 400

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월      True
2016년6월     False
2016년7월      True
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월     True
2016년12월    False
총계           True
통계           True
Name: 제해자수, dtype: bool

In [65]:
df[df2['제해자수'] > 400]

<ipython-input-65-f01473c8f1e9>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df2['제해자수'] > 400]

          사고(건)  사망(명)  부상(명)
연월
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년7월     227      9    460
2016년8월     230      7    490
2016년11월    200      5    418

In [66]:
df2['제해자수'] <= 400

연월
2016년1월      True
2016년2월      True
2016년3월     False
2016년4월     False
2016년5월     False
2016년6월      True
2016년7월     False
2016년8월     False
2016년9월      True
2016년10월     True
2016년11월    False
2016년12월     True
총계          False
통계          False
Name: 제해자수, dtype: bool

In [67]:
df2[df2['제해자수'] <= 400]

          사고(건)  사망(명)  부상(명)  제해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년6월     200     12    362   374
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년12월    168      4    364   368

In [74]:
df['사망(명)'] == 7

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [77]:
df2[df2['사망(명)'] == 7]

         사고(건)  사망(명)  부상(명)  제해자수
연월
2016년3월    217      7    435   442
2016년4월    216      7    419   426
2016년8월    230      7    490   497

In [78]:
df2['사망(명)'].isin([7])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
총계          False
통계          False
Name: 사망(명), dtype: bool

In [79]:
df2['사망(명)'].isin([7, 10])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월     True
2016년11월    False
2016년12월    False
총계          False
통계          False
Name: 사망(명), dtype: bool

In [81]:
df2['사망(명)'].isin([7])

          사고(건)  사망(명)  부상(명)  제해자수
연월
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년8월     230      7    490   497
2016년10월    183     10    367   377

In [85]:
df2[(df2['사망(명)'].isin([7])) | (df2['부상(명)'] > 350)]

          사고(건)  사망(명)  부상(명)   제해자수
연월
2016년1월     192      5    387    392
2016년3월     217      7    435    442
2016년4월     216      7    419    426
2016년5월     239     13    522    535
2016년6월     200     12    362    374
2016년7월     227      9    460    469
2016년8월     230      7    490    497
2016년10월    183     10    367    377
2016년11월    200      5    418    423
2016년12월    168      4    364    368
총계         2433     98   4899   4997
통계         9732    392  19596  19988

In [88]:
df2.index.str.contains('3')

array([False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False])

In [86]:
df2[df2.index.str.contains('3')]

         사고(건)  사망(명)  부상(명)  제해자수
연월
2016년3월    217      7    435   442